# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "slim", "~> 4.1"
gem "sinatra", "~> 2.1"
gem "sinatra-contrib", "~> 2.1"
gem "puma", "~> 5.6"
gem "solargraph", "~> 0.44.3"
gem "rubocop", "~> 1.25"
gem "rufo", "~> 0.13.0"

gem "sqlite3", "~> 1.4"
gem "bcrypt", "~> 3.1"

gem "sassc", "~> 2.4"

gem "irb", "~> 1.4"

gem "rmagick", "~> 4.2"

gem "redcarpet", "~> 3.5"
